# Generated by Django 5.2.9 on 2025-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(db_index=True, max_length=512)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('country', models.CharField(db_index=True, max_length=10)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('popularity_metrics', models.JSONField()),
                ('popularity_score', models.FloatField(db_index=True, default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('workflow', 'platform', 'country')},
            },
        ),
    ]
